export const LOGIN_SUCCESS = 'cozmo/App/LOGIN_SUCCESS';
export const LOGIN_WITH_GOOGLE_SUCCESS = 'cozmo/App/LOGIN_WITH_GOOGLE_SUCCESS';
export const SIGNUP_WITH_GOOGLE_SUCCESS = 'cozmo/App/SIGNUP_WITH_GOOGLE_SUCCESS';
export const LOGOUT_SUCCESS = 'cozmo/App/LOGOUT_SUCCESS';
export const LOGOUT = 'cozmo/App/LOGOUT';
export const HANDLE_SESSION_STATE = 'cozmo/App/HANDLE_SESSION_STATE';

export const UPDATE_USER_PLAN = 'cozmo/App/UPDATE_USER_PLAN';

export const ADD_ALERT = 'cozmo/App/ADD_ALERT';
export const REMOVE_ALERT = 'cozmo/App/REMOVE_ALERT';

export const CHACHE_MULTICALENDAR_DATA = 'cozmo/App/CHACHE_MULTICALENDAR_DATA';

export const FETCH_PROPERTIES_BASIC_INFO = 'cozmo/App/FETCH_PROPERTIES_BASIC_INFO';
export const FETCH_PROPERTIES_BASIC_INFO_SUCCESS = 'cozmo/App/FETCH_PROPERTIES_BASIC_INFO_SUCCESS';

export const FETCH_CLEANERS_BASIC_INFO = 'cozmo/App/FETCH_CLEANERS_BASIC_INFO';
export const FETCH_CLEANERS_BASIC_INFO_SUCCESS = 'cozmo/App/FETCH_CLEANERS_BASIC_INFO_SUCCESS';

export const FETCH_TEMPLATES = 'cozmo/App/FETCH_TEMPLATES';
export const FETCH_TEMPLATES_SUCCESS = 'cozmo/App/FETCH_TEMPLATES_SUCCESS';
export const FETCH_TEMPLATES_ERROR = 'cozmo/App/FETCH_TEMPLATES_ERROR';

export const CHUNK_FAILED_TO_LOAD = 'cozmo/App/CHUNK_FAILED_TO_LOAD';

export const UPDATE_USER = 'cozmo/App/UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'cozmo/App/UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'cozmo/App/UPDATE_USER_ERROR';

export const UPDATE_WINDOW_SIZE = 'cozmo/App/UPDATE_WINDOW_SIZE';
