export const FETCH_RESERVATIONS = 'cozmo/Reservations/FETCH_RESERVATIONS';
export const FETCH_RESERVATIONS_SUCCESS = 'cozmo/Reservations/FETCH_RESERVATIONS_SUCCESS';
export const FETCH_RESERVATIONS_ERROR = 'cozmo/Reservations/FETCH_RESERVATIONS_ERROR';

export const FETCH_RESERVATION = 'cozmo/Reservations/FETCH_RESERVATION';
export const FETCH_RESERVATION_SUCCESS = 'cozmo/Reservations/FETCH_RESERVATION_SUCCESS';
export const FETCH_RESERVATION_ERROR = 'cozmo/Reservations/FETCH_RESERVATION_ERROR';

export const FETCH_RESERVATION_MESSAGES = 'cozmo/Reservations/FETCH_RESERVATION_MESSAGES';
export const FETCH_RESERVATION_MESSAGES_SUCCESS = 'cozmo/Reservations/FETCH_RESERVATION_MESSAGES_SUCCESS';
export const FETCH_RESERVATION_MESSAGES_ERROR = 'cozmo/Reservations/FETCH_RESERVATION_MESSAGES_ERROR';

export const FETCH_RESERVATION_EVENTS= 'cozmo/Reservations/FETCH_RESERVATION_EVENTS';
export const FETCH_RESERVATION_EVENTS_SUCCESS = 'cozmo/Reservations/FETCH_RESERVATION_EVENTS_SUCCESS';
export const FETCH_RESERVATION_EVENTS_ERROR = 'cozmo/Reservations/FETCH_RESERVATION_EVENTS_ERROR';

export const DELETE_RESERVATION = 'cozmo/Reservations/DELETE_RESERVATION';
export const DELETE_RESERVATION_SUCCESS = 'cozmo/Reservations/DELETE_RESERVATION_SUCCESS';
export const DELETE_RESERVATION_ERROR = 'cozmo/Reservations/DELETE_RESERVATION_ERROR';

export const ADD_RESERVATION = 'cozmo/Reservations/ADD_RESERVATION';
export const ADD_RESERVATION_SUCCESS = 'cozmo/Reservations/ADD_RESERVATION_SUCCESS';
export const ADD_RESERVATION_ERROR = 'cozmo/Reservations/ADD_RESERVATION_ERROR';

export const EDIT_RESERVATION = 'cozmo/Reservations/EDIT_RESERVATION';
export const EDIT_RESERVATION_SUCCESS = 'cozmo/Reservations/EDIT_RESERVATION_SUCCESS';
export const EDIT_RESERVATION_ERROR = 'cozmo/Reservations/EDIT_RESERVATION_ERROR';

export const EDIT_GUEST = 'cozmo/Reservations/EDIT_GUEST';
export const EDIT_GUEST_SUCCESS = 'cozmo/Reservations/EDIT_GUEST_SUCCESS';
export const EDIT_GUEST_ERROR = 'cozmo/Reservations/EDIT_GUEST_ERROR';

export const FETCH_RESERVATIONS_CALENDAR = 'cozmo/Reservations/FETCH_RESERVATIONS_CALENDAR';
export const FETCH_RESERVATIONS_CALENDAR_SUCCESS = 'cozmo/Reservations/FETCH_RESERVATIONS_CALENDAR_SUCCESS';
export const FETCH_RESERVATIONS_CALENDAR_ERROR = 'cozmo/Reservations/FETCH_RESERVATIONS_CALENDAR_ERROR';
export const POPULATE_RESERVATION_CALENDAR_FROM_CACHE = 'cozmo/Reservations/POPULATE_RESERVATION_CALENDAR_FROM_CACHE';

export const FETCH_RESERVATIONS_CALENDAR_PROPERTY = 'cozmo/Reservations/FETCH_RESERVATIONS_CALENDAR_PROPERTY';
export const FETCH_RESERVATIONS_CALENDAR_PROPERTY_SUCCESS = 'cozmo/Reservations/FETCH_RESERVATIONS_CALENDAR_PROPERTY_SUCCESS';
export const FETCH_RESERVATIONS_CALENDAR_PROPERTY_ERROR = 'cozmo/Reservations/FETCH_RESERVATIONS_CALENDAR_PROPERTY_ERROR';

export const SEND_MESSAGE = 'cozmo/Reservations/SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'cozmo/Reservations/SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR = 'cozmo/Reservations/SEND_MESSAGE_ERROR';

export const CHANGE_DISPLAY = 'cozmo/Reservations/CHANGE_DISPLAY';

export const FETCH_QUOTE = 'cozmo/Reservations/FETCH_QUOTE';
export const FETCH_QUOTE_SUCCESS = 'cozmo/Reservations/FETCH_QUOTE_SUCCESS';
export const FETCH_QUOTE_ERROR = 'cozmo/Reservations/FETCH_QUOTE_ERROR';

export const CREATE_BLOCKING = 'cozmo/Reservations/CREATE_BLOCKING';
export const CREATE_BLOCKING_SUCCESS = 'cozmo/Reservations/CREATE_BLOCKING_SUCCESS';
export const CREATE_BLOCKING_ERROR = 'cozmo/Reservations/CREATE_BLOCKING_ERROR';

export const DELETE_BLOCKING = 'cozmo/Reservations/DELETE_BLOCKING';
export const DELETE_BLOCKING_SUCCESS = 'cozmo/Reservations/DELETE_BLOCKING_SUCCESS';
export const DELETE_BLOCKING_ERROR = 'cozmo/Reservations/DELETE_BLOCKING_ERROR';

export const CREATE_SEASONAL_RATING = 'cozmo/Reservations/CREATE_SEASONAL_RATING';
export const CREATE_SEASONAL_RATING_SUCCESS = 'cozmo/Reservations/CREATE_SEASONAL_RATING_SUCCESS';
export const CREATE_SEASONAL_RATING_ERROR = 'cozmo/Reservations/CREATE_SEASONAL_RATING_ERROR';

export const CREATE_CUSTOM_RATING = 'cozmo/Reservations/CREATE_CUSTOM_RATING';
export const CREATE_CUSTOM_RATING_SUCCESS = 'cozmo/Reservations/CREATE_CUSTOM_RATING_SUCCESS';
export const CREATE_CUSTOM_RATING_ERROR = 'cozmo/Reservations/CREATE_CUSTOM_RATING_ERROR';

export const SET_CALENDAR_VIEW = 'cozmo/Reservations/SET_CALENDAR_VIEW';
export const SET_CALENDAR_CURRENT_DATE = 'cozmo/Reservations/SET_CALENDAR_CURRENT_DATE';

export const OPEN_ICAL_EVENT = 'cozmo/Reservations/OPEN_ICAL_EVENT';
export const OPEN_ICAL_EVENT_SUCCESS = 'cozmo/Reservations/OPEN_ICAL_EVENT_SUCCESS';
